### ISSUE TITLE
Please make the extension available via PyPi

### ISSUE THREAD

**Issue by remal** [MadLittleMods/markdown-icons#12]
I haven't been able to find PyPi package name in the documentation.

Please upload the extension on PuPi, as it will be much easier to install the extension from PyPi.

**Comment by sander76** [comment]
Search for markdown-iconfonts

**Comment by remal** [comment]
Is it up-to-date? Has any CI solution been set up for the project?

**Comment by MadLittleMods** [comment]
@remal See https://github.com/MadLittleMods/markdown-icons/pull/11

Closing in favor of https://github.com/MadLittleMods/markdown-icons/issues/10
