### ISSUE TITLE
Put the package on PyPi

### ISSUE THREAD

**Issue by sander76** [MadLittleMods/markdown-icons#6]
Are you willing to publish this on pypi ?
I am also ok doing it myself.

Please let me know.

**Comment by MadLittleMods** [comment]
@sander76

 - Does this package still work with the latest Python markdown? https://github.com/Python-Markdown/markdown
 - I am not really up to supporting this if a bug arises. Are you interested in becoming a contribtor?
 - Can you link some docs on adding something to PyPi?
    - Perhaps you can submit the package and also add me as an owner

**Comment by sander76** [comment]
@MadLittleMods I assume it still works. I have a rather old mkdocs config which I am upgrading to the latest release. 
I will give it a go.

I am interested in becoming a contributor and trying to maintain this...

**Comment by sander76** [comment]
@MadLittleMods I can confirm it works with the latest release of markdown/mkdocs.
As far as I am concerned the only thing needed here is pushing it up to pypi.
If you make me a contributor to this repo I can do that for you (and add you as an owner)

**Comment by MadLittleMods** [comment]
@sander76 I added you as collaborator. We hould add some CI to make tagged releases get pushed to PyPi?

I am biased to using GitLab CI (I work at GitLab) and familiar with it, https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/

**Comment by sander76** [comment]
@MadLittleMods I will. If you want to move to GitLab, I am totally fine with that.

Are you okay if I do a first pypi upload ? (even though no CI is added yet.)

**Comment by MadLittleMods** [comment]
@sander76 Let's just get this setup right and add CI first

TravisCI is also fine with me. Any preferences?

**Comment by sander76** [comment]
@MadLittleMods no preferences. I only know TravisCI, but don't mind something else at all.

**Comment by MadLittleMods** [comment]
@sander76 This project is now setup as CI/CD only on GitLab, https://gitlab.com/MadLittleMods/markdown-icons

This means that any change in the GitHub repo here will be mirrored to GitLab and a GitLab CI pipeline ran, https://gitlab.com/MadLittleMods/markdown-icons/pipelines

Docs on GitLab CI, https://docs.gitlab.com/ee/ci/yaml/

Create a PR with a `.gitlab-ci.yml` so we can discuss
